### PR TITLE
Additional buttons for handhelds Legion Go and OneXPlayer.

### PR DESCRIPTION
**Pull request by CasperH2O**
Several new buttons used by the new Lenovo Legion Go and two that I missed last time for the OneXPlayer.

### CODE REVIEW

**Comment by CasperH2O** [comment]
Hey @Shinmera , another set. There's been some developments, multiple OEMs are now using M1 and M2, perhaps we should remove the ROG Ally prefix for those?

**Comment by CasperH2O** [comment]
Hey @Shinmera is this PR OK or missing something? Is it just a matter of finding the time to sort it (I can relate)?

**Comment by Shinmera** [comment]
Fell by the wayside again, sorry about that. Will try to look into it in the coming days.

**Comment by CasperH2O** [comment]
Ah, excellent! We were aiming for a public release this weekend and it would be lovely to include the full set of icons. No rush though, it's ready when it's ready. 😇

**Comment by Shinmera** [comment]
Done. Good luck for the release. In the future if you need things urgently, the contribution guide includes a short explanation on how to add glyphs into the font yourself.

**Comment by CasperH2O** [comment]
@Shinmera thank you! I'll keep that in mind for next time and give it a go.

**Pull request merged**
