### PR TITLE
Additional buttons for gamepad and Steam Deck.

### PR DESCRIPTION
**Pull request by CasperH2O**
As discussed in #2 , additional buttons we'd like to use in Handheld Companion.

### CODE REVIEW

**Comment by Shinmera** [comment]
Thanks, will get to adding them into the font soon.

**Comment by Shinmera** [comment]
Ok, they're now in. I had to fix up all of the SVGs though, as they were not in the correct size and were missing the margins. Some also were composed out of multiple shapes, rather than a singular shape.

Please for future PRs ensure that each SVG is of the same document size as the existing ones. That makes importing them into the font a lot easier.

**Comment by CasperH2O** [comment]
@Shinmera thanks for the merge and the excellent feedback. I'll make sure to incorporate your feedback on the format for next round. 

Perhaps something to add to the readme for future contributions? Shape size n x n pixels, n pixels margin, single shape, black color (#00000 ?) and transparent?

**Comment by CasperH2O** [comment]
@Shinmera is it possible you overwrote your initial options menu icon (circular shape with 3 horizontal lines) with the SteamDeck one? 

Edit: Nevermind, it's now called burger menu. All good!

afbeelding

**Comment by Shinmera** [comment]
No. That one's called the Burger Menu.

**Pull request merged**
